#!/bin/bash

# Extract Resource IDs from UniFi Backup File
# This script parses a UniFi backup file and extracts resource IDs for Terraform import

set -e

BACKUP_FILE="${1:-../backup/unifi_os_backup_*.unifi}"
OUTPUT_FILE="${2:-import-ids.txt}"

if [ ! -f "$BACKUP_FILE" ] && [ -z "$(ls $BACKUP_FILE 2>/dev/null)" ]; then
    echo "❌ Error: Backup file not found: $BACKUP_FILE"
    echo "Usage: $0 [backup-file] [output-file]"
    exit 1
fi

# Get the actual backup file path if glob was used
if [ -z "$(ls $BACKUP_FILE 2>/dev/null)" ]; then
    BACKUP_FILE=$(ls $BACKUP_FILE 2>/dev/null | head -1)
fi

echo "📦 Extracting resource IDs from: $BACKUP_FILE"
echo "📝 Output file: $OUTPUT_FILE"
echo ""

# Create Python script to extract IDs
python3 << 'PYTHON_SCRIPT' > "$OUTPUT_FILE"
import gzip
import json
import sys
import os

backup_file = sys.argv[1] if len(sys.argv) > 1 else None

if not backup_file:
    # Find backup file
    backup_dir = os.path.join(os.path.dirname(__file__), '..', 'backup')
    backup_files = [f for f in os.listdir(backup_dir) if f.endswith('.unifi')]
    if backup_files:
        backup_file = os.path.join(backup_dir, backup_files[0])
    else:
        print("❌ No backup file found")
        sys.exit(1)

print(f"📦 Parsing backup file: {backup_file}")
print("")

try:
    with gzip.open(backup_file, 'rb') as f:
        data = json.load(f)

    print("# Terraform Import IDs Extracted from UniFi Backup")
    print("# Generated by extract-ids-from-backup.sh")
    print("")

    # Networks (VLANs)
    if 'networks' in data:
        print("## Networks (VLANs)")
        for network in data['networks']:
            name = network.get('name', 'unknown')
            _id = network.get('_id', '')
            vlan_id = network.get('vlan', '')
            print(f"# {name} (VLAN {vlan_id})")
            print(f"unifi_network.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    # WLANs
    if 'wlans' in data:
        print("## WLANs")
        for wlan in data['wlans']:
            name = wlan.get('name', 'unknown')
            _id = wlan.get('_id', '')
            print(f"# {name}")
            print(f"unifi_wlan.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    # Firewall Groups
    if 'firewallgroups' in data:
        print("## Firewall Groups")
        for group in data['firewallgroups']:
            name = group.get('name', 'unknown')
            _id = group.get('_id', '')
            print(f"# {name}")
            print(f"unifi_firewall_group.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    # DNS Records
    if 'dns_records' in data:
        print("## DNS Records")
        for record in data['dns_records']:
            name = record.get('name', 'unknown')
            _id = record.get('_id', '')
            print(f"# {name}")
            print(f"unifi_dns_record.{name.lower().replace('.', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    # Static Routes
    if 'static_routes' in data or 'routing' in data:
        routes = data.get('static_routes', data.get('routing', {}).get('static_routes', []))
        if routes:
            print("## Static Routes")
            for route in routes:
                name = route.get('name', 'unknown')
                _id = route.get('_id', '')
                print(f"# {name}")
                print(f"unifi_static_route.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
            print("")

    # User Groups
    if 'usergroups' in data:
        print("## User Groups")
        for group in data['usergroups']:
            name = group.get('name', 'unknown')
            _id = group.get('_id', '')
            print(f"# {name}")
            print(f"unifi_user_group.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    # Firewall Rules
    if 'firewallrules' in data:
        print("## Firewall Rules")
        for rule in data['firewallrules']:
            name = rule.get('name', rule.get('ruleset', 'unknown'))
            _id = rule.get('_id', '')
            print(f"# {name}")
            print(f"unifi_firewall_rule.{name.lower().replace(' ', '_').replace('-', '_')} = \"{_id}\"")
        print("")

    print("# Summary")
    print(f"# Total Networks: {len(data.get('networks', []))}")
    print(f"# Total WLANs: {len(data.get('wlans', []))}")
    print(f"# Total Firewall Groups: {len(data.get('firewallgroups', []))}")
    print(f"# Total DNS Records: {len(data.get('dns_records', []))}")
    print(f"# Total Static Routes: {len(data.get('static_routes', data.get('routing', {}).get('static_routes', [])))}")
    print(f"# Total User Groups: {len(data.get('usergroups', []))}")
    print(f"# Total Firewall Rules: {len(data.get('firewallrules', []))}")

except Exception as e:
    print(f"❌ Error parsing backup file: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
PYTHON_SCRIPT
"$BACKUP_FILE"

echo "✅ Extraction complete! IDs saved to: $OUTPUT_FILE"
echo ""
echo "📋 Next steps:"
echo "1. Review the extracted IDs in $OUTPUT_FILE"
echo "2. Update your Terraform configuration files with the correct resource names"
echo "3. Use the IDs to import resources: terraform import <resource_type>.<name> <id>"

